service: language

provider:
  name: aws
  runtime: java11

package:
  artifact: target/sls-spellchecker-1.0.1.jar

functions:
  checkSpelling:
    handler: com.isahb.slsspellchecker.Handler
    environment: 
      JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    memorySize: 2048
    timeout: 60
    # url:
    #   cors: true
    events:
      - http:
          path: check
          method: POST
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false